// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Table.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("Domain.Table.Table", b =>
                {
                    b.OwnsOne("Domain.Table.ValueObject.LockStatus", "LockStatus", b1 =>
                        {
                            b1.Property<int>("TableId")
                                .HasColumnType("integer");

                            b1.Property<int?>("IdUser")
                                .HasColumnType("integer")
                                .HasColumnName("IdUsuario");

                            b1.Property<int>("StatusLock")
                                .HasColumnType("integer")
                                .HasColumnName("StatusBloqueio");

                            b1.Property<DateTime>("TimeLock")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("TempoBloqueio");

                            b1.HasKey("TableId");

                            b1.ToTable("Mesas");

                            b1.WithOwner()
                                .HasForeignKey("TableId");
                        });

                    b.Navigation("LockStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
